name: Fastygs
favicon: null
layout_spectrum: 0.6723254162352532
typography_spectrum: 0.9121548240073025
title: Můj web
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0672174806240946
  lightness: 0.13678618730045855
  saturation: 0.158023230265826
  rhythmicContrast: 0.13858346012420952
purpose: []
